# Javascript Node CircleCI 2.1 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: cypress/base:8
        environment:
          ## this enables colors in the output
          TERM: xterm
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/cypress-test

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-deps-{{ .Branch }}-{{ checksum "package.json" }}
            - v1-deps-{{ .Branch }}
            - v1-deps
      - run:
          name: Install Dependencies
          command: yarn --ignore-engines install && yarn install
      - save_cache:
          key: v1-deps-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - ~/.cache  ## cache both yarn and Cypress!

      # run tests! 
      - run:
          name: run Cypress
          command: |
            rm -R -f cypress/reports && mkdir cypress/reports && mkdir cypress/reports/mochareports
            $(yarn bin)/cypress run 
          when: always
      - run:
          name: Merge and generate reports
          command: |
            npx mochawesome-merge cypress/reports/mocha/*.json > cypress/reports/mochareports/report.json
            npx marge cypress/reports/mochareports/report.json -f report -o cypress/reports/mochareports
            cp -R cypress/screenshots cypress/reports/mochareports/screenshots
          when: always   
      - store_artifacts:
          path: ~/cypress-test/cypress/screenshots
      - store_artifacts:
          path: ~/cypress-test/cypress/videos
      - store_artifacts:
          path: ~/cypress-test/cypress/reports
