export const ELEMENTS = {
  createAccount: '#create-account-link',
  chooseLaguage: '.dropdown__button',
  name: '#name',
  lastName: '#lastName',
  originCountry: '.dropdown__button',
  taxpayerRegistry: '#taxpayerRegistry',
  cpf: '#cpf',
  email: '#email',
  emailConfirmation: '#email-confirmation',
  password: '#password',
  useTerms: '[type="checkbox"]',
  createAccountButton: '#button-create-account',
  errorMessage: '.error-message',
  errorData: '.tip',
  accessAccountButton: '#access-account-link',
  alertError: '.alert',
  forgotPasswordLink: '#forgot-password-link',
  forgotPasswordButton: '#button-send',
  alertForgotPassword:'.forgot-password__feedback',
  recoverPasswordCpf: '#recover-with-cpf-link',
}